; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
;Configuración del baudrate del monitor serie
monitor_speed = 115200

; Filtros recomendados para el envío de comandos
monitor_filters = 
    send_on_enter          ; Espera a que presiones Enter para mandar toda la línea (clave para comandos shs)
    esp32_exception_decoder ; Decodifica errores/crashes del ESP32 si ocurren

monitor_echo = yes         ; Muestra en pantalla lo que vas tecleando